name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3

      # Step 2: Debug output folder
      - name: Debug output folder
        run: |
          echo "Checking if the output folder exists and listing its contents:"
          if [ -d output ]; then
            echo "Output folder exists."
            ls -al output
          else
            echo "Output folder does not exist!"
            exit 1
          fi

      # Step 3: Copy output to a temporary directory
      - name: Copy output folder to temp
        run: |
          mkdir -p temp-output
          cp -r output/* temp-output/ || echo "No files to copy from output"

      # Step 4: Switch to gh-pages branch
      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      # Step 5: Clear old files in gh-pages root
      - name: Clear old files
        run: |
          rm -rf ./*

      # Step 6: Deploy files to gh-pages root
      - name: Deploy files to root
        run: |
          cp -r ../temp-output/* . || echo "No files to deploy"

      # Step 7: Commit and push changes to gh-pages
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy rendered IG to gh-pages root" || echo "No changes to commit"
          git push origin gh-pages

      # Step 8: Cleanup temp directory
      - name: Cleanup temp directory
        run: |
          rm -rf ../temp-output
