name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Checkout gh-pages branch
      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      # Step 3: Copy output to docs
      - name: Copy output to docs
        run: |
          rm -rf docs # Clean the existing docs folder
          mkdir -p docs
          cp -r output/* docs/

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update docs with new output files" || echo "No changes to commit"
          git push origin gh-pages
